/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary-fixed": "#d6e3ff",
        "secondary-fixed-dim": "#e9c176",
        "on-tertiary-fixed": "#2b1701",
        "outline-variant": "#c5c6cd",
        "inverse-primary": "#b9c7e4",
        "on-surface-variant": "#44474d",
        "secondary": "#775a19",
        "primary-fixed-dim": "#b9c7e4",
        "on-error": "#ffffff",
        "tertiary": "#000000",
        "error": "#ba1a1a",
        "surface-container-highest": "#e4e2e4",
        "surface-container-lowest": "#ffffff",
        "on-primary-fixed-variant": "#39475f",
        "tertiary-fixed": "#ffdcbd",
        "surface-variant": "#e4e2e4",
        "surface": "#fbf9fb",
        "inverse-surface": "#303032",
        "on-tertiary-container": "#9f7d5b",
        "surface-dim": "#dbd9db",
        "tertiary-fixed-dim": "#e7bf99",
        "on-secondary-fixed-variant": "#5d4201",
        "inverse-on-surface": "#f2f0f2",
        "primary-container": "#0d1c32",
        "surface-bright": "#fbf9fb",
        "secondary-fixed": "#ffdea5",
        "on-secondary-fixed": "#261900",
        "on-secondary": "#ffffff",
        "surface-container": "#efedef",
        "error-container": "#ffdad6",
        "on-background": "#1b1b1d",
        "tertiary-container": "#2b1701",
        "on-primary": "#ffffff",
        "background": "#fbf9fb",
        "on-tertiary-fixed-variant": "#5d4124",
        "outline": "#75777e",
        "surface-bone": "#F4F1EA",
        "on-primary-fixed": "#0d1c32",
        "surface-container-low": "#f5f3f5",
        "surface-tint": "#515f78",
        "on-surface": "#1b1b1d",
        "on-primary-container": "#76849f",
        "on-error-container": "#93000a",
        "on-secondary-container": "#785a1a",
        "outline-navy": "rgba(10, 25, 47, 0.1)",
        "primary": "#000000",
        "on-tertiary": "#ffffff",
        "secondary-container": "#fed488",
        "surface-container-high": "#eae7ea"
      },
      fontFamily: {
        "display-lg-mobile": ["Hanken Grotesk", "sans-serif"],
        "display-lg": ["Hanken Grotesk", "sans-serif"],
        "body-lg": ["Hanken Grotesk", "sans-serif"],
        "label-caps": ["Hanken Grotesk", "sans-serif"],
        "body-md": ["Hanken Grotesk", "sans-serif"],
        "headline-md": ["Hanken Grotesk", "sans-serif"],
        "headline-sm": ["Hanken Grotesk", "sans-serif"],
        "headline-lg": ["Hanken Grotesk", "sans-serif"],
        "label-sm": ["Hanken Grotesk", "sans-serif"]
      },
      fontSize: {
        "display-lg-mobile": ["44px", { "lineHeight": "48px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "display-lg": ["72px", { "lineHeight": "80px", "letterSpacing": "-0.03em", "fontWeight": "700" }],
        "body-lg": ["18px", { "lineHeight": "30px", "letterSpacing": "0em", "fontWeight": "400" }],
        "label-caps": ["12px", { "lineHeight": "16px", "letterSpacing": "0.12em", "fontWeight": "700" }],
        "body-md": ["16px", { "lineHeight": "26px", "letterSpacing": "0em", "fontWeight": "400" }],
        "headline-md": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "headline-sm": ["24px", { "lineHeight": "32px", "letterSpacing": "0em", "fontWeight": "600" }],
        "headline-lg": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "600" }],
        "label-sm": ["11px", { "lineHeight": "14px", "letterSpacing": "0.02em", "fontWeight": "500" }]
      },
      spacing: {
        "unit-md": "16px",
        "unit-lg": "32px",
        "container-max": "1200px",
        "unit-sm": "8px",
        "unit-xl": "64px",
        "unit-xs": "4px",
        "gutter": "32px",
        "section-desktop": "128px",
        "section-mobile": "64px",
        "stack-md": "16px",
        "stack-sm": "8px",
        "stack-lg": "32px",
        "section-padding-mobile": "64px",
        "section-padding-desktop": "120px"
      }
    },
  },
  plugins: [],
}
